#!/usr/bin/env node
import { readFileSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import Database from 'better-sqlite3'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = join(HERE, '../..')
const DB_PATH = join(REPO, 'apps/mobile/assets/nutrition.db')
const MAPPED_JSON = join(REPO, 'docs', 'data', 'indian-dishes.mapped.json')

// ---------------------------------------------------------------------------
// Supplemental ingredient rows.
//
// Plain tea and brewed coffee are genuinely absent from BOTH bundled corpora
// (IFCT 2017 subset: no tea/coffee rows; the shipped USDA release: only
// ready-to-drink and herbal variants). The dish curation needs them for
// Masala Chai, Milk Tea and Filter Coffee, so they ship as USDA FoodData
// Central reference values in a dedicated `fdc_supplemental` source — never
// misrepresented as verbatim SR Legacy rows. The `fdc_%` source pattern means
// the existing USDA source, resolver and mapping loader pick them up as
// ordinary usda: foods with zero special-casing, and the source_id `SUP-`
// namespace can never collide with a real FDC id.
// ---------------------------------------------------------------------------
const SUPPLEMENTAL_FOODS = [
  {
    sourceId: 'SUP-TEA-001',
    name: 'Tea, black, brewed, plain',
    energy: 1, protein: 0, fat: 0, carb: 0.3, fiber: 0, sugar: 0, sodium: 3,
    note: 'USDA FDC reference values for plain brewed black tea (~1 kcal/100 g).',
  },
  {
    sourceId: 'SUP-COF-001',
    name: 'Coffee, brewed, plain',
    energy: 1, protein: 0.1, fat: 0, carb: 0, fiber: 0, sugar: 0, sodium: 2,
    note: 'USDA FDC reference values for plain brewed coffee (~1 kcal/100 g).',
  },
]

function ensureSupplementalFoods(db) {
  const schemaRow = db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='foods'").get()
  if (!schemaRow) return 0 // fixture/food-less DB — nothing to do
  let inserted = 0
  const insertFood = db.prepare(`
    INSERT INTO foods (source, source_id, name, basis, basis_confidence,
                       energy_kcal, protein_g, fat_g, sat_fat_g, carb_g, fiber_g,
                       sugar_g, sodium_mg, completeness_score, popularity_rank,
                       license, updated_at)
    VALUES ('fdc_supplemental', ?, ?, 'per_100g', 'reviewed',
            ?, ?, ?, NULL, ?, ?, ?, ?, 1.0, 50,
            'Public domain (USDA FoodData Central reference values)', ?)
  `)
  const now = Date.now()
  const tx = db.transaction(() => {
    for (const food of SUPPLEMENTAL_FOODS) {
      const existing = db.prepare("SELECT id FROM foods WHERE source = 'fdc_supplemental' AND source_id = ?").get(food.sourceId)
      if (existing) continue
      const info = insertFood.run(food.sourceId, food.name, food.energy, food.protein, food.fat, food.carb, food.fiber, food.sugar, food.sodium, now)
      const rowId = Number(info.lastInsertRowid)
      // Keep the FTS indexes in sync so search finds the new rows.
      const ftsTables = db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name IN ('food_fts','food_fts_trigram')").all()
      for (const t of ftsTables) {
        if (t.name === 'food_fts') db.prepare('INSERT INTO food_fts (rowid, name, brand, synonyms) VALUES (?, ?, NULL, ?)').run(rowId, food.name, food.sourceId)
        if (t.name === 'food_fts_trigram') db.prepare('INSERT INTO food_fts_trigram (rowid, name) VALUES (?, ?)').run(rowId, food.name)
      }
      inserted += 1
    }
  })
  tx()
  return inserted
}

async function main() {
  const src = await readFile(join(REPO, 'packages/db-adapter/src/schema.ts'), 'utf8')
  const grab = (name) => {
    const m = new RegExp(`export const ${name} = \\\`([\\s\\S]*?)\\\``).exec(src)
    return m ? m[1] : ''
  }
  
  const DISH_KB_SCHEMA = grab('DISH_KB_SCHEMA')
  const DISH_KB_FTS_SCHEMA = grab('DISH_KB_FTS_SCHEMA')
  
  const db = new Database(DB_PATH)
  
  db.exec('DROP TABLE IF EXISTS dish_aliases;')
  db.exec('DROP TABLE IF EXISTS dish_fts;')
  db.exec('DROP TABLE IF EXISTS dish_fts_trigram;')
  db.exec('DROP TABLE IF EXISTS dish_definitions;')
  
  db.exec(DISH_KB_SCHEMA)
  db.exec(DISH_KB_FTS_SCHEMA)
  
  let dishes = []
  try {
    dishes = JSON.parse(readFileSync(MAPPED_JSON, 'utf8'))
  } catch {
    dishes = JSON.parse(readFileSync(join(REPO, 'docs', 'indian-dishes.seed.v0.1 (1).json'), 'utf8'))
  }

  // Name-derived ingredient suggestions for DRAFT dishes (reviewed pin list,
  // generated by dish-ingredient-suggestions.mjs). They ride inside the
  // recipe template so the dish composer can pre-seed a real, DB-verified
  // ingredient list the user confirms — instead of showing generic labels
  // like "primary_vegetable" with no identity.
  let suggestions = {}
  try {
    suggestions = JSON.parse(readFileSync(join(HERE, 'dish-ingredient-suggestions.json'), 'utf8'))
  } catch {
    suggestions = {}
  }
  let injected = 0
  
  const insertDish = db.prepare(`
    INSERT INTO dish_definitions (
      id, search_rowid, canonical_name, category, family, parent_dish_id,
      cooking_methods_json, yield_model_json, recipe_template_json,
      portion_model_json, uncertainty_model_json, resolver_config_json, record_status
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `)
  
  const insertAlias = db.prepare('INSERT INTO dish_aliases (dish_id, alias, is_search_term) VALUES (?, ?, ?)')
  const insertFts = db.prepare('INSERT INTO dish_fts (rowid, canonical_name, aliases, search_terms) VALUES (?, ?, ?, ?)')
  const insertFtsTri = db.prepare('INSERT INTO dish_fts_trigram (rowid, canonical_name, aliases) VALUES (?, ?, ?)')

  const templateWithSuggestions = (dish) => {
    const template = dish.recipeTemplate || {}
    // Only skip dishes that are already FULLY resolvable (all required slots
    // mapped): a draft with just water/salt mapped but a generic
    // "primary_vegetable" gains far more from real name-derived suggestions
    // than it loses from hiding the trivial mapped slots.
    const requiredSlots = (dish.recipeTemplate?.ingredientSlots ?? []).filter((slot) => slot.required)
    const requiredAllMapped = requiredSlots.length > 0 && requiredSlots.every((slot) =>
      ['AUTO_MAPPED', 'MANUAL_OVERRIDE'].includes(slot.nutritionMapping?.mappingStatus) &&
      slot.nutritionMapping?.canonicalFoodId)
    const entry = suggestions[dish.id]
    if (requiredAllMapped || !entry || dish.provenance?.recordStatus === 'CURATED') return template
    if (Array.isArray(template.ingredientSuggestions) && template.ingredientSuggestions.length > 0) return template
    injected += 1
    return { ...template, ingredientSuggestions: entry.suggestions }
  }
  
  let count = 0
  const tx = db.transaction(() => {
    for (const dish of dishes) {
      count++
      insertDish.run(
        dish.id,
        count,
        dish.canonicalName,
        dish.category,
        dish.family,
        dish.parentDishId || null,
        JSON.stringify(dish.cooking?.methods || []),
        JSON.stringify(dish.cooking?.yieldModel || {}),
        JSON.stringify(templateWithSuggestions(dish)),
        JSON.stringify(dish.portionModel || {}),
        JSON.stringify(dish.uncertaintyModel || {}),
        JSON.stringify(dish.resolver || {}),
        dish.provenance?.recordStatus || 'DRAFT_CURATED'
      )
      
      const aliases = dish.aliases || []
      const searchTerms = dish.searchTerms || []
      
      for (const alias of aliases) {
        insertAlias.run(dish.id, alias, searchTerms.includes(alias) ? 1 : 0)
      }
      
      insertFts.run(count, dish.canonicalName, aliases.join(' '), searchTerms.join(' '))
      insertFtsTri.run(count, dish.canonicalName, aliases.join(' '))
    }
  })
  
  tx()
  const supplemental = ensureSupplementalFoods(db)
  db.close()
  console.log(`Compiled ${count} dishes into ${DB_PATH} (${injected} draft dishes carry ingredient suggestions; ${supplemental} supplemental ingredients ensured).`)
}

main().catch(err => {
  console.error(err)
  process.exit(1)
})
