export const INDIAN_ALIASES: Record<string, string> = {
  'chana dal': 'bengal gram dal',
  'urad dal': 'black gram dal',
  'moong dal': 'green gram dal',
  'masoor dal': 'lentil dal',
  'kala chana': 'bengal gram whole',
  'sarson ka saag': 'mustard greens',
  'gulab jamun': 'fried milk balls in syrup',
  'kamal kakdi': 'lotus stem',
  'khus khus': 'poppy seeds',
  'tej patta': 'bay leaf',
  'chakri phool': 'star anise',
  'char magaz': 'melon seeds',
  
  'arhar': 'red gram',
  'toor': 'red gram',
  'tuvar': 'red gram',
  'chana': 'chickpea',
  'kabuli': 'chickpea',
  'rajma': 'kidney bean',
  'urad': 'black gram',
  'moong': 'green gram',
  'masoor': 'red lentil',
  'lobia': 'cowpea',
  'matar': 'pea',
  'methi': 'fenugreek',
  'jeera': 'cumin',
  'haldi': 'turmeric',
  'dhaniya': 'coriander',
  'saunf': 'fennel',
  'rai': 'mustard',
  'sarson': 'mustard',
  'ajwain': 'carom',
  'hing': 'asafoetida',
  'dalchini': 'cinnamon',
  'elaichi': 'cardamom',
  'laung': 'clove',
  'jaiphal': 'nutmeg',
  'kasoori': 'fenugreek',
  'amchur': 'mango powder',
  'poha': 'flattened rice',
  'sabudana': 'tapioca pearl',
  'suji': 'semolina',
  'rawa': 'semolina',
  'besan': 'gram flour',
  'maida': 'refined flour',
  'atta': 'wheat flour',
  'dahi': 'yogurt',
  'paneer': 'cottage cheese',
  'ghee': 'clarified butter',
  'makhan': 'butter',
  'tel': 'oil',
  'shakkar': 'sugar',
  'gud': 'jaggery',
  'namak': 'salt',
  'mirch': 'chili',
  'pyaaz': 'onion',
  'lasun': 'garlic',
  'adrak': 'ginger',
  'aloo': 'potato',
  'tamatar': 'tomato',
  'gajar': 'carrot',
  'mooli': 'radish',
  'baingan': 'eggplant',
  'bhindi': 'okra',
  'karela': 'bitter gourd',
  'lauki': 'bottle gourd',
  'kaddu': 'pumpkin',
  'tinda': 'apple gourd',
  'parwal': 'pointed gourd',
  'palak': 'spinach',
  'bathua': 'chenopodium',
  'pudina': 'mint',
  'nimbu': 'lemon',
  'narial': 'coconut',
  'kaju': 'cashew',
  'badam': 'almond',
  'pista': 'pistachio',
  'akhrot': 'walnut',
  'mungfali': 'peanut',
  'kishmish': 'raisin',
  'anjeer': 'fig',
  'khajoor': 'date',
  'seb': 'apple',
  'kela': 'banana',
  'santra': 'orange',
  'angoor': 'grape',
  'aam': 'mango',
  'amrood': 'guava',
  'papita': 'papaya',
  'ananas': 'pineapple',
  'tarbooz': 'watermelon',
  'kharbooza': 'muskmelon',
  'chikoo': 'sapota',
  'sitaphal': 'custard apple',
  'jamun': 'java plum',
  'ber': 'jujube',
  'imli': 'tamarind',
  'amla': 'gooseberry',
  'makhana': 'fox nut',
  'chapati': 'roti',
  'phulka': 'roti',
  'paratha': 'flatbread',
  'naan': 'flatbread',
  'puri': 'fried flatbread',
  'bhatura': 'fried flatbread',
  'kulcha': 'flatbread',
  'dosa': 'crepe',
  'idli': 'steamed cake',
  'vada': 'fritter',
  'upma': 'savory porridge',
  'khichdi': 'rice and lentil porridge',
  'pulao': 'pilaf',
  'biryani': 'mixed rice',
  'raita': 'yogurt dip',
  'chutney': 'sauce',
  'achar': 'pickle',
  'papad': 'cracker',
  'sambar': 'lentil stew',
  'rasam': 'soup',
  'matki': 'moth bean',
  'lobhia': 'cowpea',
  'rongi': 'cowpea',
  'chowli': 'cowpea',
  'kulthi': 'horse gram',
  'vatana': 'dried pea',
  'chole': 'chickpea curry',
  'rajgira': 'amaranth',
  'kuttu': 'buckwheat',
  'bajra': 'pearl millet',
  'jowar': 'sorghum',
  'ragi': 'finger millet',
  'makki': 'corn',
  'bhutta': 'corn on the cob',
  'gobi': 'cauliflower',
  'pattagobi': 'cabbage',
  'bandhgobi': 'cabbage',
  'kheera': 'cucumber',
  'kakdi': 'cucumber',
  'shalgam': 'turnip',
  'chukandar': 'beetroot',
  'arbi': 'taro',
  'suran': 'elephant foot yam',
  'jimikand': 'elephant foot yam',
  'shakarkandi': 'sweet potato',
  'bhe': 'lotus stem',
  'singhara': 'water chestnut',
  'sabza': 'basil seeds',
  'chia': 'chia seeds',
  'ajinomoto': 'msg',
  'jaipatri': 'mace',
  'javitri': 'mace',
  'kalonji': 'nigella seeds',
  'til': 'sesame seeds',
  'sonth': 'dry ginger',
  'bael': 'wood apple',
  'phalsa': 'grewia',
  'karonda': 'carandas',
  'kokum': 'garcinia indica',
  'gond': 'edible gum',
  'katira': 'tragacanth gum',
  'misri': 'rock sugar',
  'khand': 'muscovado',
  'bura': 'powdered sugar',
  'chashni': 'sugar syrup',
  'rabdi': 'sweetened condensed milk',
  'khoya': 'milk solids',
  'mawa': 'milk solids',
  'chhena': 'curdled milk',
  'malai': 'cream',
  'chaach': 'buttermilk',
  'mattha': 'buttermilk',
  'lassi': 'sweet buttermilk',
  'shrikhand': 'sweet strained yogurt',
  'barfi': 'milk fudge',
  'peda': 'milk fudge',
  'laddoo': 'sweet ball',
  'halwa': 'sweet pudding',
  'kheer': 'rice pudding',
  'payasam': 'rice pudding',
  'rasgulla': 'syrup filled cheese balls',
  'rasmalai': 'cheese dumplings in cream',
  'sandesh': 'cheese fudge',
  'chum chum': 'cheese sweet',
  'petha': 'ash gourd sweet',
  'gajak': 'sesame sweet',
  'chikki': 'peanut brittle'
}

/** Hindi-script aliases are kept alongside transliterations, never erased. */
const HINDI_ALIASES: Record<string, string> = {
  'अरहर': 'red gram', 'तूर': 'red gram', 'चना': 'chickpea', 'राजमा': 'kidney bean',
  'मूंग': 'green gram', 'मसूर': 'red lentil', 'दही': 'yogurt', 'पनीर': 'cottage cheese',
  'घी': 'clarified butter', 'आटा': 'wheat flour', 'चावल': 'rice', 'रोटी': 'roti',
  'आलू': 'potato', 'प्याज': 'onion', 'टमाटर': 'tomato', 'पालक': 'spinach',
  'भिंडी': 'okra', 'बैंगन': 'eggplant', 'लौकी': 'bottle gourd', 'करेला': 'bitter gourd',
  'हल्दी': 'turmeric', 'जीरा': 'cumin', 'धनिया': 'coriander', 'नमक': 'salt',
}

export const INDIAN_ALIAS_FIXTURES: Readonly<Record<string, string>> = Object.freeze({
  ...INDIAN_ALIASES,
  ...HINDI_ALIASES,
})
// Ensure multi-word aliases are processed first by sorting by descending length.
const ALIAS_KEYS = Object.keys(INDIAN_ALIAS_FIXTURES).sort((a, b) => b.length - a.length)

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

export function normalizeIndianAliases(query: string): string {
  let normalized = query.toLowerCase()

  for (const key of ALIAS_KEYS) {
    // `\\b` is ASCII-oriented and fails around Devanagari. Unicode boundaries
    // avoid replacements inside a larger token in every supported script.
    const regex = new RegExp(`(^|[^\\p{L}\\p{N}])${escapeRegex(key)}(?=$|[^\\p{L}\\p{N}])`, 'gu')
    if (regex.test(normalized)) {
      normalized = normalized.replace(regex, (_match, boundary: string) => `${boundary}${INDIAN_ALIAS_FIXTURES[key]!}`)
    }
  }

  return normalized
}
