import type { DbAdapter, RunResult, SqlValue } from '@nutai/db-adapter'
import * as SQLite from 'expo-sqlite'
// GENERATED by tools/indian-dishes/build-sqlite.mjs alongside nutrition.db.
import { REQUIRED_CORPUS_REVISION } from '../data/corpus-revision'

/**
 * The expo-sqlite implementation of the shared DbAdapter interface.
 *
 * This file lives in apps/mobile and NOT in @nutai/db-adapter, deliberately.
 * `packages/*` must stay importable under bare Node with zero React Native
 * surface (PLAN.md §4.1) so the eval harness can run the real pipeline; an
 * `import 'expo-sqlite'` in that package would fail the node-purity gate. This
 * app is the only place allowed to hold React Native imports.
 *
 * The Node implementation lives at @nutai/db-adapter/node. Both satisfy the same
 * interface, which is what makes "it worked in the harness" mean something on
 * device.
 */
/**
 * Which logical database an adapter talks to — used only for diagnostics so a
 * native failure names the file and the statement instead of surfacing a raw
 * Java NPE (device QA 2026-10: NativeDatabase.prepareAsync NPE on Android).
 */
type DbLabel = 'user.db' | 'nutrition.db' | 'ifct.db'

/**
 * Turn a raw expo-sqlite rejection into one that names the database, the
 * operation and the statement. The original message is always preserved.
 *
 * The Android release NPE has a specific known shape (prepareAsync on a native
 * handle whose JS wrapper was garbage-collected — expo-sqlite 57 destroys the
 * SHARED native database when ANY JS wrapper is collected, see the retention
 * note below), so we recognize it and say what it means instead of letting a
 * bare "NullPointerException" reach a screen.
 */
function describeDbError(label: DbLabel, op: string, sql: string | null, error: unknown): Error {
  const raw = error instanceof Error ? error.message : String(error)
  const statement = sql == null ? '' : `("${sql.length > 120 ? `${sql.slice(0, 120)}…` : sql}")`
  const isReleasedHandleNpe =
    /NullPointerException/i.test(raw) &&
    /NativeDatabase|NativeStatement/i.test(raw) &&
    !/closed/i.test(raw)
  const hint = isReleasedHandleNpe
    ? ' — the native SQLite handle was destroyed while this connection was still in use ' +
      '(a duplicate JS wrapper for the same file was garbage-collected). ' +
      'All app handles are retained via openXxxDb() singletons; if you see this, ' +
      'a new SQLite.openDatabaseAsync call path was added without retention.'
    : ''
  return new Error(`[nut-ai/db] ${label} ${op}${statement} failed: ${raw}${hint}`)
}

class ExpoDbAdapter implements DbAdapter {
  constructor(
    private readonly db: SQLite.SQLiteDatabase,
    private readonly label: DbLabel,
  ) {}

  async all<T = Record<string, SqlValue>>(sql: string, params: readonly SqlValue[] = []): Promise<T[]> {
    try {
      return (await this.db.getAllAsync(sql, params as SQLite.SQLiteBindValue[])) as T[]
    } catch (error) {
      throw describeDbError(this.label, 'all', sql, error)
    }
  }

  async get<T = Record<string, SqlValue>>(sql: string, params: readonly SqlValue[] = []): Promise<T | null> {
    try {
      return ((await this.db.getFirstAsync(sql, params as SQLite.SQLiteBindValue[])) as T | null) ?? null
    } catch (error) {
      throw describeDbError(this.label, 'get', sql, error)
    }
  }

  async run(sql: string, params: readonly SqlValue[] = []): Promise<RunResult> {
    try {
      const r = await this.db.runAsync(sql, params as SQLite.SQLiteBindValue[])
      return { changes: r.changes, lastInsertRowId: r.lastInsertRowId }
    } catch (error) {
      throw describeDbError(this.label, 'run', sql, error)
    }
  }

  async exec(sql: string): Promise<void> {
    try {
      await this.db.execAsync(sql)
    } catch (error) {
      throw describeDbError(this.label, 'exec', sql, error)
    }
  }

  async transaction<T>(fn: (tx: DbAdapter) => Promise<T>): Promise<T> {
    let result!: T
    try {
      await this.db.withTransactionAsync(async () => {
        result = await fn(this)
      })
    } catch (error) {
      // Errors thrown by `fn` itself may arrive here too; describeDbError keeps
      // the original message, so the innermost cause stays legible.
      if (error instanceof Error && error.message.startsWith('[nut-ai/db]')) throw error
      throw describeDbError(this.label, 'transaction', null, error)
    }
    return result
  }

  async close(): Promise<void> {
    await this.db.closeAsync()
  }
}

/**
 * GC-retention guard for every SQLite handle this adapter ever opens (Android
 * release QA 2026-10).
 *
 * expo-sqlite 57 dedupes native databases per file: every JS
 * SQLiteDatabase wrapper for the same path wraps ONE Kotlin NativeDatabase.
 * When a JS wrapper is garbage-collected, expo-modules-core fires
 * sharedObjectDidRelease() — which calls ref.close() with NO refcount check —
 * destroying the shared native handle for every other wrapper. Any later
 * prepareAsync then dies with a raw java.lang.NullPointerException.
 *
 * The app previously created throwaway wrappers via direct openUserDb() calls
 * (onboarding persist, scan recents, assistant, dish composer); collecting one
 * of those killed user.db for Progress/Routines mid-session.
 *
 * Two layers of defense:
 * 1. openUserDb() is now itself a promise-deduped singleton — duplicate
 *    wrappers are no longer created in the first place.
 * 2. Every opened handle is retained here for the process lifetime (the app
 *    opens exactly three databases; the memory cost is the handles only), so
 *    even a future duplicate-open path can never be garbage-collected.
 */
const retainedHandles = new Set<SQLite.SQLiteDatabase>()

function retain(db: SQLite.SQLiteDatabase): SQLite.SQLiteDatabase {
  retainedHandles.add(db)
  return db
}

/**
 * The writable user database.
 *
 * Promise-deduped process-wide singleton (Android release QA 2026-10): every
 * direct call used to open a NEW JS wrapper over the SAME native handle (the
 * native side dedupes by path), and garbage-collecting any throwaway wrapper
 * destroyed the native database for the whole app — surfacing as the
 * NativeDatabase.prepareAsync NPE on Progress/Routines. Callers may keep
 * awaiting this function freely; they all share one retained handle.
 */
let userOpenPromise: Promise<DbAdapter> | null = null

export async function openUserDb(): Promise<DbAdapter> {
  if (!userOpenPromise) {
    userOpenPromise = (async () => {
      const db = retain(await SQLite.openDatabaseAsync('user.db'))
      await db.execAsync('PRAGMA foreign_keys = ON;')
      // P3-D10: align with the node adapter — WAL gives the single-connection
      // write path the same journal-mode behavior on native as in tests/tools.
      await db.execAsync('PRAGMA journal_mode = WAL;')
      return new ExpoDbAdapter(db, 'user.db') as DbAdapter
    })().catch((error) => {
      userOpenPromise = null
      throw error
    })
  }
  return userOpenPromise
}

/**
 * The read-only bundled nutrition corpus.
 *
 * The 4.7 MB artifact built by tools/nutrition-data ships as an app asset and is
 * imported into the SQLite directory on first launch, because FTS5 needs a real
 * writable path for its temporary files. The app never writes to it — the copy
 * exists for SQLite's benefit, not ours, and a corpus update replaces the file
 * wholesale rather than mutating it.
 *
 * WITHOUT THIS IMPORT the app opens an EMPTY database of the same name, and every
 * food silently falls to the AI-estimate path — which looks exactly like a
 * resolver bug while actually being a missing asset. Hence `nutritionCorpusInfo`
 * below, so that failure is legible rather than mysterious.
 */
let nutritionOpenPromise: Promise<DbAdapter> | null = null
let ifctOpenPromise: Promise<DbAdapter> | null = null

export async function openNutritionDb(): Promise<DbAdapter> {
  if (!nutritionOpenPromise) {
    nutritionOpenPromise = (async () => {
      await SQLite.importDatabaseFromAssetAsync('nutrition.db', {
        assetId: require('../../assets/nutrition.db'),
        // Idempotent by name. Re-copying 4.7 MB on every cold start would be a
        // visible delay for nothing.
        forceOverwrite: false,
      })
      const db = retain(await SQLite.openDatabaseAsync('nutrition.db'))
      // Owner QA 2026-10: "table exists" was the only freshness probe, so an
      // install that ever imported an early/partial corpus kept it forever —
      // the dish browser showed a handful of rows under a "362 identities"
      // headline. The corpus now ships a content-derived revision inside its
      // own build_manifest (mirrored into the bundle as
      // REQUIRED_CORPUS_REVISION); any mismatch force-reimports the asset.
      // The corpus is generated data, never user data, so re-copying is safe.
      let revision: string | null = null
      try {
        const row = await db.getFirstAsync<{ value: string }>(
          "SELECT value FROM build_manifest WHERE key = 'corpus_revision'",
        )
        revision = row?.value ?? null
      } catch {
        revision = null // no manifest table at all → stale beyond rescue
      }
      const needsFreshCopy = revision !== REQUIRED_CORPUS_REVISION
      if (needsFreshCopy) {
        await db.closeAsync()
        await SQLite.importDatabaseFromAssetAsync('nutrition.db', {
          assetId: require('../../assets/nutrition.db'),
          forceOverwrite: true,
        })
        const freshDb = retain(await SQLite.openDatabaseAsync('nutrition.db'))
        return new ExpoDbAdapter(freshDb, 'nutrition.db')
      }
      return new ExpoDbAdapter(db, 'nutrition.db')
    })().catch((error) => {
      nutritionOpenPromise = null
      throw error
    })
  }
  return nutritionOpenPromise
}

/** The authorized IFCT corpus has a separate asset and provenance lifecycle. */
export async function openIfctDb(): Promise<DbAdapter> {
  if (!ifctOpenPromise) {
    // The corpus is generated, not user data. Overwrite once per process so an
    // install that previously imported the two-row development fixture receives
    // the current 542-row authorized corpus after an app update.
    ifctOpenPromise = (async () => {
      await SQLite.importDatabaseFromAssetAsync('ifct.db', {
        assetId: require('../../assets/ifct.db'),
        forceOverwrite: true,
      })
      const db = retain(await SQLite.openDatabaseAsync('ifct.db'))
      return new ExpoDbAdapter(db, 'ifct.db')
    })().catch((error) => {
      ifctOpenPromise = null
      throw error
    })
  }
  return ifctOpenPromise
}

export function resetCorpusPromises(): void {
  nutritionOpenPromise = null
  ifctOpenPromise = null
}

/** Test-only: forget the cached singletons (handles stay retained). */
export function resetUserDbPromiseForTests(): void {
  userOpenPromise = null
}

/**
 * Confirm the corpus actually arrived.
 *
 * A build shipped without the asset answers every query with zero rows, which is
 * indistinguishable at the UI from "no match found". Surfacing the row count
 * turns a silent, confusing failure into an obvious one.
 */
/** P1-10: corpus-honesty metrics shipped INSIDE the artifact they describe. */
export interface DishKbHonesty {
  dishes: number
  /** Dishes whose every ingredient slot resolves to a corpus food id. */
  fullyMapped: number | null
  /** Dishes with a verified numeric cooked yield. */
  yieldVerified: number | null
  builtAt: string | null
}

async function readDishKbHonesty(db: DbAdapter): Promise<DishKbHonesty | null> {
  try {
    const dishRows = await db.get<{ c: number }>('SELECT COUNT(*) c FROM dish_definitions')
    const dishes = dishRows?.c ?? 0
    // Older bundles predate the dish_kb_* manifest keys — report what we know
    // (the count) and leave the honesty split null rather than guessing.
    const manifest = await db.all<{ key: string; value: string }>(
      "SELECT key, value FROM build_manifest WHERE key IN ('dish_kb_fully_mapped','dish_kb_yield_verified','dish_kb_built_at')",
    )
    const pick = (key: string) => manifest.find((row) => row.key === key)?.value ?? null
    const fully = pick('dish_kb_fully_mapped')
    const verified = pick('dish_kb_yield_verified')
    return {
      dishes,
      fullyMapped: fully == null ? null : Number(fully),
      yieldVerified: verified == null ? null : Number(verified),
      builtAt: pick('dish_kb_built_at'),
    }
  } catch {
    return null
  }
}

export async function nutritionCorpusInfo(
  db: DbAdapter,
): Promise<{ foods: number; portions: number; dishes: number; builtAt: string | null; dishKb: DishKbHonesty | null }> {
  const foods = await db.get<{ c: number }>('SELECT COUNT(*) c FROM foods')
    const portions = await db.get<{ c: number }>('SELECT COUNT(*) c FROM food_portions')
    const built = await db.get<{ value: string }>(
      "SELECT value FROM build_manifest WHERE key = 'built_at'",
    )
  // P2-14: surface the bundled dish knowledge base size alongside the food
  // corpora. Older dish-less bundles simply report 0.
  // P1-10: alongside the count, ship the fully-mapped / yield-verified split
  // from the artifact's own build_manifest so the app header cannot claim more
  // than the shipped DB justifies.
  const dishKb = await readDishKbHonesty(db)
  return { foods: foods?.c ?? 0, portions: portions?.c ?? 0, dishes: dishKb?.dishes ?? 0, builtAt: built?.value ?? null, dishKb }
}

export async function ifctCorpusInfo(
  db: DbAdapter,
): Promise<{ foods: number; version: string | null }> {
  const foods = await db.get<{ c: number }>("SELECT COUNT(*) c FROM foods WHERE source = 'ifct'")
    const version = await db.get<{ value: string }>(
      "SELECT value FROM build_manifest WHERE key = 'version'",
    )
  return { foods: foods?.c ?? 0, version: version?.value ?? null }
}
