// GENERATED by tools/indian-dishes/build-sqlite.mjs — do not edit by hand.
// The content-derived revision of the nutrition.db this build shipped.
// openNutritionDb() compares the on-disk copy's build_manifest.corpus_revision
// against this constant and force-reimports the asset on any mismatch, so an
// app update can never keep serving a stale corpus (owner QA 2026-10: the
// Indian-dishes browser showed a handful of rows under a "362 identities"
// headline because an early import was never refreshed).
export const REQUIRED_CORPUS_REVISION = '7059ce2cf6f8'
